"""split customer gstin_pan into gstin and pan

Revision ID: 298d22e146c0
Revises: 2aa88299e97e
Create Date: 2026-08-16 16:51:42.274385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298d22e146c0'
down_revision: Union[str, Sequence[str], None] = '2aa88299e97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.add_column('customers', sa.Column('pan', sa.String(length=10), nullable=True))
    op.drop_column('customers', 'gstin_pan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gstin_pan', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('customers', 'pan')
    op.drop_column('customers', 'gstin')
    # ### end Alembic commands ###
